name: Run default tests

on:
    workflow_dispatch:
    workflow_call:

defaults:
    run:
        shell: bash

env:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
    run-release:
        continue-on-error: false
        strategy:
            fail-fast: true
            matrix:
                os: [ 'ubuntu-latest' ]

        runs-on: ${{ matrix.os }}
        name: Publish artifacts
        concurrency:
            group: run-release-${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
            cancel-in-progress: true
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Setup environment
                uses: ./.github/actions/setup-environment
                with:
                    cache-read-only: ${{ github.ref_name != 'main' }}

            - name: Publish artifacts
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
                echo "New version: ${VERSION}"
                echo "Github Username: ${GITHUB_ACTOR}"

                ./gradlew -Pversion=${VERSION} publishAllPublicationsToGithubPackagesRepository
